export const SKILLS_LIST = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "SQL",
  "REST APIs",
  "GraphQL",
  "Git",
  "Docker",
  "AWS",
  "System Design",
  "Data Structures",
  "Algorithms",
  "Agile",
  "Scrum",
  "Product Management",
  "UX Design",
  "Figma",
  "CI/CD",
  "Testing",
  "Machine Learning",
  "Data Analysis",
  "Communication",
  "Leadership",
  "Problem Solving",
  "Technical Writing",
  "Javanese",
] as const;

export type SkillId = (typeof SKILLS_LIST)[number];
